server:
  port: 10001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: food-login  #本服务的名称
  cloud:                           #注册到nacos
    nacos:
      discovery:
        server-addr: 47.94.20.182:8848
        register-enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
dubbo:
  scan:
    base-packages: com.csh.food.dubbo.service
  application:
    architecture:
    name: dubbo-food-login
    id: dubbo-food-login-admin
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: nacos://47.94.20.182:8848
  protocol:
    name: dubbo
    port: 20880
  cloud:
    subscribed-services: ''