server:
  port: 11001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: food-test-center   #本服务的名称
  cloud:                           #注册到nacos
    nacos:
      discovery:
        server-addr: 47.94.20.182:8848
management:
  endpoints:
    web:
      exposure:
        include: "*"
dubbo:
  application:
    name: dubbo-food-test
    id: dubbo-food-login-admin
    qos-enable: false
    qos-accept-foreign-ip: false
  registry:
    address: nacos://47.94.20.182:8848
  consumer:
    timeout: 4000